both:	
	gcc simpleClient.c -o client -lpthread
	gcc simpleServer.c -o server -lpthread

client: simpleClient.c
	gcc simpleClient.c -o client -lpthread

server: simpleServer.c
	gcc simpleServer.c -o server -lpthread